
/* Squad beyond Javascript Body欄：scriptタグを含めて全て貼り付け */
(function () {
  function bootAojiru() {
    var root = document.getElementById('aojiru-lp');
    if (!root || root.dataset.aojiruReady === '1') return;
    root.dataset.aojiruReady = '1';

    const stage=root.querySelector('#aojiru-stage'),game=root.querySelector('#aojiru-game'),basket=root.querySelector('#aojiru-basket'),meter=root.querySelector('#aojiru-meter'),scoreEl=root.querySelector('#aojiru-score'),timeEl=root.querySelector('#aojiru-time'),comboEl=root.querySelector('#aojiru-combo'),comboNum=root.querySelector('#aojiru-comboNum'),bonusEl=root.querySelector('#aojiru-bonus'),end=root.querySelector('#aojiru-end'),replay=root.querySelector('#aojiru-replay'),intro=root.querySelector('#aojiru-intro');
    let running=false,items=[],score=0,combo=0,time=15,spawnCount=0,startAt=0,raf,timer,spawnTimer;
    const spriteMap={'item-yogurt.webp':1,'item-broccoli.webp':2,'item-carrot.webp':3,'item-barley.webp':4,'item-vitamin.webp':5,'item-fiber.webp':6,'item-donut.webp':7,'item-fries.webp':8,'item-cake.webp':9,'item-chips.webp':10};
    const types=[{c:'lacto collectible',art:'col-yogurt',img:'item-yogurt.webp',t:'ヨーグルト',p:9},{c:'green collectible',art:'col-broccoli',img:'item-broccoli.webp',t:'ブロッコリー',p:7},{c:'green collectible',art:'col-carrot',img:'item-carrot.webp',t:'にんじん',p:7},{c:'green collectible',art:'col-greens',img:'item-barley.webp',t:'大麦若葉',p:7},{c:'vit collectible',art:'col-vitamin',img:'item-vitamin.webp',t:'ビタミン',p:7},{c:'green collectible',art:'col-fiber',img:'item-fiber.webp',t:'食物繊維',p:7},{c:'bad hazard',art:'haz-donut',img:'item-donut.webp',t:'NG！ドーナツ',p:-8},{c:'bad hazard',art:'haz-fries',img:'item-fries.webp',t:'NG！ポテト',p:-8},{c:'bad hazard',art:'haz-cake',img:'item-cake.webp',t:'NG！ケーキ',p:-8},{c:'bad hazard',art:'haz-chips',img:'item-chips.webp',t:'NG！スナック',p:-8}];
    function move(clientX){if(!running)return;const r=game.getBoundingClientRect(),w=basket.offsetWidth;let x=Math.max(w/2,Math.min(r.width-w/2,clientX-r.left));basket.style.left=x+'px'}
    game.addEventListener('pointermove',e=>move(e.clientX));game.addEventListener('pointerdown',e=>{move(e.clientX);game.setPointerCapture?.(e.pointerId)});
    function spawn(forceGood=false){if(!running)return;const r=game.getBoundingClientRect(),guided=spawnCount<2,goodCount=6,data=(forceGood||guided)?types[spawnCount%goodCount]:types[Math.floor(Math.random()*types.length)];const el=document.createElement('div');el.className='item '+data.c+' '+data.art;el.innerHTML='<span class="spriteCrop"><span class="cuteSprite sprite-'+spriteMap[data.img]+'"></span></span><span class="itemLabel">'+data.t+'</span>';const size=Math.max(76,Math.min(100,r.width*.22));el.style.width=el.style.height=size+'px';const x=guided?(r.width-size)/2:10+Math.random()*(r.width-size-20),speed=r.height*(.27+Math.random()*.07),startY=-size-18;game.insertBefore(el,basket);const item={el,x,y:startY,startY,born:performance.now(),size,speed,p:data.p};el.style.transform=`translate3d(${x}px,${startY}px,0)`;items.push(item);spawnCount++;}
    function floating(x,y,text,bad=false){const f=document.createElement('div');f.className='float';f.textContent=text;f.style.left=x+'px';f.style.top=y+'px';if(bad)f.style.color='#db3c31';game.appendChild(f);setTimeout(()=>f.remove(),850)}
    function hit(it){it.el.remove();if(it.p>0){score=Math.min(100,score+it.p);combo++;basket.classList.add('catch');setTimeout(()=>basket.classList.remove('catch'),170);floating(it.x+it.size/2,it.y,'GOOD!  +'+it.p);if(combo>=2){comboNum.textContent=combo;comboEl.classList.add('show');setTimeout(()=>comboEl.classList.remove('show'),420)}}else{score=Math.max(0,score+it.p);combo=0;floating(it.x+it.size/2,it.y,'NG！お菓子は避けよう',true);stage.classList.remove('shake');void stage.offsetWidth;stage.classList.add('shake')}meter.style.width=score+'%';scoreEl.textContent=score;}
    function frame(ts){if(!running)return;const br=basket.getBoundingClientRect(),gr=game.getBoundingClientRect();items=items.filter(it=>{it.y=it.startY+it.speed*((ts-it.born)/1000);it.el.style.transform=`translate3d(${it.x}px,${it.y}px,0)`;const ir={left:gr.left+it.x,right:gr.left+it.x+it.size,top:gr.top+it.y,bottom:gr.top+it.y+it.size};const catchLine=br.top+18;if(ir.bottom>=catchLine&&ir.top<=br.bottom-5&&ir.right>=br.left+8&&ir.left<=br.right-8){hit(it);return false}if(it.y>gr.height+12){it.el.remove();if(it.p>0)combo=0;return false}return true});raf=requestAnimationFrame(frame)}
    function start(){const guide=root.querySelector('#aojiru-instruction');guide.style.animation='none';void guide.offsetWidth;guide.style.animation='';root.querySelector('#aojiru-skip').hidden=false;cancelAnimationFrame(raf);clearInterval(timer);clearInterval(spawnTimer);items.forEach(i=>i.el.remove());items=[];score=0;combo=0;time=15;spawnCount=0;meter.style.width='0';scoreEl.textContent='0';timeEl.textContent='15';end.classList.remove('show');end.setAttribute('aria-hidden','true');basket.style.left='50%';running=true;startAt=performance.now();spawn();spawnTimer=setInterval(()=>spawn(time<=4),550);raf=requestAnimationFrame(frame);timer=setInterval(()=>{const next=Math.max(0,Math.ceil(15-(performance.now()-startAt)/1000));if(next!==time){time=next;timeEl.textContent=time;if(time===4){bonusEl.classList.remove('on');void bonusEl.offsetWidth;bonusEl.classList.add('on')}}if(time<=0)finish()},250)}
    function showStory(){stage.hidden=true;root.querySelector('#aojiru-story').hidden=false;root.querySelector('.sticky').hidden=false;root.querySelector('#aojiru-result').textContent='今回のチャレンジ：'+score+' ポイント獲得！';window.scrollTo(0,0);root.querySelector('#aojiru-storyTitle').focus({preventScroll:true});} root.querySelector('#aojiru-skip').addEventListener('click',()=>{if(running){finish()}else{showStory();root.querySelector('#aojiru-result').textContent='おいしい1杯のひみつ';}}); function finish(){if(!running)return;running=false;clearInterval(timer);clearInterval(spawnTimer);cancelAnimationFrame(raf);items.forEach(i=>i.el.remove());items=[];setTimeout(showStory,400)}
    const demoStart=root.querySelector('#aojiru-start');
    function beginFromDemo(e){if(running||intro.classList.contains('hide'))return;intro.classList.add('hide');start();if(e&&e.type==='pointerdown'){move(e.clientX);try{stage.setPointerCapture(e.pointerId)}catch(_){}}}
    demoStart.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();beginFromDemo(e)});
    demoStart.addEventListener('click',()=>beginFromDemo());
    stage.addEventListener('pointermove',e=>{if(running&&stage.hasPointerCapture?.(e.pointerId))move(e.clientX)});
    replay.addEventListener('click',()=>{root.querySelector('#aojiru-story').hidden=true;root.querySelector('.sticky').hidden=true;stage.hidden=false;window.scrollTo(0,0);start()});let hiddenAt=0;document.addEventListener('visibilitychange',()=>{if(!running)return;if(document.hidden){hiddenAt=performance.now();clearInterval(spawnTimer);clearInterval(timer);cancelAnimationFrame(raf)}else if(hiddenAt){const delta=performance.now()-hiddenAt;startAt+=delta;items.forEach(i=>i.born+=delta);hiddenAt=0;spawnTimer=setInterval(()=>spawn(time<=4),550);raf=requestAnimationFrame(frame);timer=setInterval(()=>{time=Math.max(0,Math.ceil(15-(performance.now()-startAt)/1000));timeEl.textContent=time;if(time<=0)finish()},250)}});document.addEventListener('keydown',e=>{if(running&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const r=basket.getBoundingClientRect();move(r.left+r.width/2+(e.key==='ArrowLeft'?-35:35))}});window.addEventListener('resize',()=>{basket.style.left='50%'});
  
    root.querySelector('#aojiru-skip-intro').addEventListener('click', function () {
      root.querySelector('#aojiru-skip').click();
    });
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', bootAojiru, { once: true });
  } else {
    bootAojiru();
  }
})();
